name: Test-Devops-NG
on:
  push:
      branches:
        -  main
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      -
        name: Devops step numerber 2
        run: echo "Hello world!"
      -
        name: Testing DEV
        run: |
          echo "Step 1..."
          echo "Step 2..."
          echo "Step 3..."
      -
        name: I am exited
        run: echo "Goodbye!"
