name: Test-Devops-md
on:
  push:
      branches:
        -  main
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      -
        name: Devops step numerber 3
        run: echo "Hello world!"
      -
        name: Testing DEVopss
        run: |
          echo "Step 1..."
          echo "Step 2..."
          echo "Step 3..."
      -
        name: I am happy
        run: echo "Goodbye!"
